routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('app.dashboard');
});

Auth::routes();

Route::group(['prefix' => 'app', 'as' => 'app.', 'middleware' => 'auth'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('doctors', DoctorController::class);
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'guard_name',
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleFormRequest;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $this->authorize('read-roles');
        $roles = Role::all();

        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create-roles');

        $permissions = Permission::all();
        return view('roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create-roles');

        $role = Role::create($request->all());
        $role->permissions()->sync($request->input('permissions', []));
        return redirect()->route('app.roles.index')->with('success', 'Roles Added');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $this->authorize('read-roles');

        $role->permissions()->get();

        return view('roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->authorize('update-roles');
        $permissions = Permission::all();
        return view('roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->authorize('update-roles');

        $role->update($request->all());

        $role->permissions()->sync($request->input('permissions', []));
        return redirect()->route('app.roles.index')->with('success', 'Roles Updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete-roles');
        $role->delete();
        return redirect()->route('app.roles.index')->with('success', 'Roles Deleted');

    }
}

app/Livewire/Roles.php
<?php

namespace App\Livewire;

use App\Models\Role;
use Livewire\Component;

class Roles extends Component
{
    public function render()
    {
        $roles = Role::all();
        return view('livewire.roles', ['roles' => $roles]);
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('app.roles.index')}}">Roles </a></li>
                <li class="breadcrumb-item"><i class="feather-chevron-right"></i></li>
                <li class="breadcrumb-item active">Roles Create</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                <form action="{{route('app.roles.store')}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <div class="form-heading">
                                <h4>Role Details</h4>
                            </div>
                        </div>
                        <div class="col-12 col-md-12 col-xl-12">
                            <div class="input-block local-forms">
                                <label>Name <span class="login-danger">*</span></label>
                                <input class="form-control" type="text" name="name" placeholder="">
                            </div>
                        </div>
                        <div class="col-12 col-md-12 col-xl-12">
                            <div class="row">
                                @foreach ($permissions as $permission)
                                <div class="col-sm-3">
                                  <label class="form-check form-check-sm form-check-custom form-check-solid me-5 me-lg-20">
                                    <input class="form-check-input" type="checkbox" value="{{$permission->id}}" name="permissions[]">
                                    <span class="form-check-label">{{$permission->name}}</span>
                                  </label>
                                  <p></p>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="doctor-submit text-end">
                                <button type="submit" class="btn btn-primary submit-form me-2">Submit</button>
                                {{-- <button type="submit" class="btn btn-primary cancel-form">Cancel</button> --}}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('app.roles.index')}}">Roles </a></li>
                <li class="breadcrumb-item"><i class="feather-chevron-right"></i></li>
                <li class="breadcrumb-item active">Roles Create</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                <form action="{{route('app.roles.update', $role->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-12">
                            <div class="form-heading">
                                <h4>Role Details</h4>
                            </div>
                        </div>
                        <div class="col-12 col-md-12 col-xl-12">
                            <div class="input-block local-forms">
                                <label>Name <span class="login-danger">*</span></label>
                                <input class="form-control" type="text" value="{{old('name', isset($role) ? $role->name : '')}}" name="name" placeholder="">
                            </div>
                        </div>
                        <div class="col-12 col-md-12 col-xl-12">
                            <div class="row">
                                @foreach ($permissions as $permission)
                                <div class="col-sm-3">
                                  <label class="form-check form-check-sm form-check-custom form-check-solid me-5 me-lg-20">
                                    <input class="form-check-input" type="checkbox" value="{{$permission->id}}" name="permissions[]" {{ (in_array($permission->id, old('permissions', [])) || isset($role) && $role->permissions->contains($permission->id)) ? 'checked' : '' }}>
                                    <span class="form-check-label">{{$permission->name}}</span>
                                  </label>
                                  <p></p>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="doctor-submit text-end">
                                <button type="submit" class="btn btn-primary submit-form me-2">Submit</button>
                                {{-- <button type="submit" class="btn btn-primary cancel-form">Cancel</button> --}}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('app.users.index')}}">Roles </a></li>
                <li class="breadcrumb-item"><i class="feather-chevron-right"></i></li>
                <li class="breadcrumb-item active">Roles List</li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">

        <div class="card card-table show-entire">
            <div class="card-body">

                <!-- Table Header -->
                <div class="page-table-header mb-2">
                    <div class="row align-items-center">
                        <div class="col">
                            <div class="doctor-table-blk">
                                <h3>Roles List</h3>
                                <div class="doctor-search-blk">
                                    <div class="top-nav-search table-search-blk">
                                        <form>
                                            <input type="text" class="form-control" placeholder="Search here">
                                            <a class="btn"><img src="{{asset('assets/img/icons/search-normal.svg')}}" alt=""></a>
                                        </form>
                                    </div>
                                    <div class="add-group">
                                        <a href="{{route('app.roles.create')}}" class="btn btn-primary add-pluss ms-2"><img src="{{asset('assets/img/icons/plus.svg')}}" alt=""></a>
                                        <a href="javascript:;" class="btn btn-primary doctor-refresh ms-2"><img src="{{asset('assets/img/icons/re-fresh.svg')}}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto text-end float-end ms-auto download-grp">
                            <a href="javascript:;" class=" me-2"><img src="{{asset('assets/img/icons/pdf-icon-01.svg')}}" alt=""></a>
                            <a href="javascript:;" class=" me-2"><img src="{{asset('assets/img/icons/pdf-icon-02.svg')}}" alt=""></a>
                            <a href="javascript:;" class=" me-2"><img src="{{asset('assets/img/icons/pdf-icon-03.svg')}}" alt=""></a>
                            <a href="javascript:;" ><img src="assets/img/icons/pdf-icon-04.svg" alt=""></a>

                        </div>
                    </div>
                </div>
                <!-- /Table Header -->

               <livewire:roles/>
            </div>
        </div>
    </div>
</div>
@endsection